---
services:
  db:
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    platform: linux/x86_64 # M1チップ対応のため追記
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: ./.docker/db/my.conf
        target: /etc/mysql/my.conf

  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    platform: linux/x86_64 # M1チップ対応のため追記
    working_dir: /var/www/src
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src

  web:
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    platform: linux/x86_64 # M1チップ対応のため追記
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./.docker/web/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./src
        target: /var/www/src

volumes:
  db:
